/* ESP32-P4 register addresses and fields used by drivers/psram_esp32p4.c.
 * 47.3, plan/phase47_esp32p4_lcd7b_ribbon.md.
 *
 * GENERATED -- do not edit by hand. Regenerate with
 *
 *     python3 tools/gen/p4_regs.py < tools/gen/p4_psram_regs.txt
 *
 * which evaluates ESP-IDF's own macros (components/soc/esp32p4/register/
 * hw_ver1 and hw_ver3, bases included) and **fails if the two revisions
 * disagree** on any address, shift or mask listed. So one table serves the
 * NANO (v1.3) and the LCD-7B (v3.2), and that is a checked fact rather than an
 * assumption. Names are IDF's, so every value can be looked up there. */
#ifndef LUGALOS_DRIVERS_ESP32P4_PSRAM_REGS_H
#define LUGALOS_DRIVERS_ESP32P4_PSRAM_REGS_H

#define SPI_MEM_S_CACHE_SCTRL_REG                    0x5008e040u
#define SPI_MEM_S_CACHE_SRAM_USR_WCMD_S              20u
#define SPI_MEM_S_CACHE_SRAM_USR_WCMD_V              0x1u
#define SPI_MEM_S_CACHE_SRAM_USR_RCMD_S              5u
#define SPI_MEM_S_CACHE_SRAM_USR_RCMD_V              0x1u
#define SPI_MEM_S_SRAM_ADDR_BITLEN_S                 14u
#define SPI_MEM_S_SRAM_ADDR_BITLEN_V                 0x3fu
#define SPI_MEM_S_CACHE_USR_SADDR_4BYTE_S            0u
#define SPI_MEM_S_CACHE_USR_SADDR_4BYTE_V            0x1u
#define SPI_MEM_S_USR_WR_SRAM_DUMMY_S                3u
#define SPI_MEM_S_USR_WR_SRAM_DUMMY_V                0x1u
#define SPI_MEM_S_SRAM_WDUMMY_CYCLELEN_S             22u
#define SPI_MEM_S_SRAM_WDUMMY_CYCLELEN_V             0x3fu
#define SPI_MEM_S_USR_RD_SRAM_DUMMY_S                4u
#define SPI_MEM_S_USR_RD_SRAM_DUMMY_V                0x1u
#define SPI_MEM_S_SRAM_RDUMMY_CYCLELEN_S             6u
#define SPI_MEM_S_SRAM_RDUMMY_CYCLELEN_V             0x3fu
#define SPI_MEM_S_SRAM_OCT_S                         21u
#define SPI_MEM_S_SRAM_OCT_V                         0x1u
#define SPI_MEM_S_SRAM_DWR_CMD_REG                   0x5008e04cu
#define SPI_MEM_S_CACHE_SRAM_USR_WR_CMD_BITLEN_S     28u
#define SPI_MEM_S_CACHE_SRAM_USR_WR_CMD_BITLEN_V     0xfu
#define SPI_MEM_S_CACHE_SRAM_USR_WR_CMD_VALUE_S      0u
#define SPI_MEM_S_CACHE_SRAM_USR_WR_CMD_VALUE_V      0xffffu
#define SPI_MEM_S_SRAM_DRD_CMD_REG                   0x5008e048u
#define SPI_MEM_S_CACHE_SRAM_USR_RD_CMD_BITLEN_S     28u
#define SPI_MEM_S_CACHE_SRAM_USR_RD_CMD_BITLEN_V     0xfu
#define SPI_MEM_S_CACHE_SRAM_USR_RD_CMD_VALUE_S      0u
#define SPI_MEM_S_CACHE_SRAM_USR_RD_CMD_VALUE_V      0xffffu
#define SPI_MEM_S_SMEM_DDR_REG                       0x5008e0d8u
#define SPI_MEM_S_SMEM_VAR_DUMMY_S                   1u
#define SPI_MEM_S_SMEM_VAR_DUMMY_V                   0x1u
#define SPI_MEM_S_SMEM_DDR_EN_S                      0u
#define SPI_MEM_S_SMEM_DDR_EN_V                      0x1u
#define SPI_MEM_S_SMEM_DDR_WDAT_SWP_S                3u
#define SPI_MEM_S_SMEM_DDR_WDAT_SWP_V                0x1u
#define SPI_MEM_S_SMEM_DDR_RDAT_SWP_S                2u
#define SPI_MEM_S_SMEM_DDR_RDAT_SWP_V                0x1u
#define SPI_MEM_S_SRAM_CMD_REG                       0x5008e044u
#define SPI_MEM_S_SDUMMY_WOUT_S                      23u
#define SPI_MEM_S_SDUMMY_WOUT_V                      0x1u
#define SPI_MEM_S_SCMD_OCT_S                         21u
#define SPI_MEM_S_SCMD_OCT_V                         0x1u
#define SPI_MEM_S_SADDR_OCT_S                        20u
#define SPI_MEM_S_SADDR_OCT_V                        0x1u
#define SPI_MEM_S_SDOUT_OCT_S                        19u
#define SPI_MEM_S_SDOUT_OCT_V                        0x1u
#define SPI_MEM_S_SDIN_OCT_S                         18u
#define SPI_MEM_S_SDIN_OCT_V                         0x1u
#define SPI_MEM_S_SDIN_HEX_S                         26u
#define SPI_MEM_S_SDIN_HEX_V                         0x1u
#define SPI_MEM_S_SDOUT_HEX_S                        27u
#define SPI_MEM_S_SDOUT_HEX_V                        0x1u
#define SPI_MEM_S_CACHE_FCTRL_REG                    0x5008e03cu
#define SPI_MEM_S_AXI_REQ_EN_S                       0u
#define SPI_MEM_S_AXI_REQ_EN_V                       0x1u
#define SPI_MEM_S_CLOSE_AXI_INF_EN_S                 31u
#define SPI_MEM_S_CLOSE_AXI_INF_EN_V                 0x1u
#define SPI_MEM_S_CTRL1_REG                          0x5008e00cu
#define SPI_MEM_S_AW_SPLICE_EN_S                     26u
#define SPI_MEM_S_AW_SPLICE_EN_V                     0x1u
#define SPI_MEM_S_AR_SPLICE_EN_S                     25u
#define SPI_MEM_S_AR_SPLICE_EN_V                     0x1u
#define SPI_MEM_S_SRAM_CLK_REG                       0x5008e050u
#define SPI_MEM_S_SCLK_EQU_SYSCLK_S                  31u
#define SPI_MEM_S_SCLK_EQU_SYSCLK_V                  0x1u
#define SPI_MEM_S_SCLKCNT_N_S                        16u
#define SPI_MEM_S_SCLKCNT_N_V                        0xffu
#define SPI_MEM_S_SCLKCNT_H_S                        8u
#define SPI_MEM_S_SCLKCNT_H_V                        0xffu
#define SPI_MEM_S_SCLKCNT_L_S                        0u
#define SPI_MEM_S_SCLKCNT_L_V                        0xffu
#define SPI_MEM_S_SMEM_TIMING_CALI_REG               0x5008e190u
#define SPI_MEM_S_SMEM_DLL_TIMING_CALI_S             5u
#define SPI_MEM_S_SMEM_DLL_TIMING_CALI_V             0x1u
#define SPI_MEM_S_TIMING_CALI_REG                    0x5008e180u
#define SPI_MEM_S_DLL_TIMING_CALI_S                  5u
#define SPI_MEM_S_DLL_TIMING_CALI_V                  0x1u
#define SPI_MEM_S_SMEM_AC_REG                        0x5008e1a0u
#define SPI_MEM_S_SMEM_CS_SETUP_S                    0u
#define SPI_MEM_S_SMEM_CS_SETUP_V                    0x1u
#define SPI_MEM_S_SMEM_CS_SETUP_TIME_S               2u
#define SPI_MEM_S_SMEM_CS_SETUP_TIME_V               0x1fu
#define SPI_MEM_S_SMEM_CS_HOLD_S                     1u
#define SPI_MEM_S_SMEM_CS_HOLD_V                     0x1u
#define SPI_MEM_S_SMEM_CS_HOLD_TIME_S                7u
#define SPI_MEM_S_SMEM_CS_HOLD_TIME_V                0x1fu
#define SPI_MEM_S_SMEM_CS_HOLD_DELAY_S               25u
#define SPI_MEM_S_SMEM_CS_HOLD_DELAY_V               0x3fu
#define SPI_MEM_S_SMEM_SPLIT_TRANS_EN_S              31u
#define SPI_MEM_S_SMEM_SPLIT_TRANS_EN_V              0x1u
#define SPI_MEM_S_SMEM_ECC_CTRL_REG                  0x5008e174u
#define SPI_MEM_S_SMEM_PAGE_SIZE_S                   18u
#define SPI_MEM_S_SMEM_PAGE_SIZE_V                   0x3u
#define SPI_MEM_S_MMU_ITEM_INDEX_REG                 0x5008e380u
#define SPI_MEM_S_MMU_ITEM_CONTENT_REG               0x5008e37cu
#define SPI1_MEM_S_CLOCK_REG                         0x5008f014u
#define SPI1_MEM_S_CLK_EQU_SYSCLK_S                  31u
#define SPI1_MEM_S_CLK_EQU_SYSCLK_V                  0x1u
#define SPI1_MEM_S_CLKCNT_N_S                        16u
#define SPI1_MEM_S_CLKCNT_N_V                        0xffu
#define SPI1_MEM_S_CLKCNT_H_S                        8u
#define SPI1_MEM_S_CLKCNT_H_V                        0xffu
#define SPI1_MEM_S_CLKCNT_L_S                        0u
#define SPI1_MEM_S_CLKCNT_L_V                        0xffu
#define SPI1_MEM_S_DDR_REG                           0x5008f0d4u
#define SPI1_MEM_S_FMEM_VAR_DUMMY_S                  1u
#define SPI1_MEM_S_FMEM_VAR_DUMMY_V                  0x1u
#define HP_SYS_CLKRST_SOC_CLK_CTRL0_REG              0x500e6014u
#define HP_SYS_CLKRST_REG_PSRAM_SYS_CLK_EN_S         31u
#define HP_SYS_CLKRST_REG_PSRAM_SYS_CLK_EN_V         0x1u
#define HP_SYS_CLKRST_PERI_CLK_CTRL00_REG            0x500e6030u
#define HP_SYS_CLKRST_REG_PSRAM_CLK_SRC_SEL_S        12u
#define HP_SYS_CLKRST_REG_PSRAM_CLK_SRC_SEL_V        0x3u
#define HP_SYS_CLKRST_REG_PSRAM_PLL_CLK_EN_S         14u
#define HP_SYS_CLKRST_REG_PSRAM_PLL_CLK_EN_V         0x1u
#define HP_SYS_CLKRST_REG_PSRAM_CORE_CLK_EN_S        15u
#define HP_SYS_CLKRST_REG_PSRAM_CORE_CLK_EN_V        0x1u
#define HP_SYS_CLKRST_REG_PSRAM_CORE_CLK_DIV_NUM_S   16u
#define HP_SYS_CLKRST_REG_PSRAM_CORE_CLK_DIV_NUM_V   0xffu
#define HP_SYS_CLKRST_HP_RST_EN0_REG                 0x500e60c0u
#define HP_SYS_CLKRST_REG_RST_EN_DUAL_MSPI_AXI_S     23u
#define HP_SYS_CLKRST_REG_RST_EN_DUAL_MSPI_AXI_V     0x1u
#define HP_SYS_CLKRST_REG_RST_EN_DUAL_MSPI_APB_S     25u
#define HP_SYS_CLKRST_REG_RST_EN_DUAL_MSPI_APB_V     0x1u
#define HP_SYS_CLKRST_ANA_PLL_CTRL0_REG              0x500e60bcu
#define HP_SYS_CLKRST_REG_MSPI_CAL_STOP_S            9u
#define HP_SYS_CLKRST_REG_MSPI_CAL_STOP_V            0x1u
#define HP_SYS_CLKRST_REG_MSPI_CAL_END_S             8u
#define HP_SYS_CLKRST_REG_MSPI_CAL_END_V             0x1u
#define PMU_RF_PWC_REG                               0x5011515cu
#define PMU_MSPI_PHY_XPD_S                           24u
#define PMU_MSPI_PHY_XPD_V                           0x1u
#define LP_CLKRST_HP_CLK_CTRL_REG                    0x50111040u
#define LP_CLKRST_HP_MPLL_500M_CLK_EN_S              28u
#define LP_CLKRST_HP_MPLL_500M_CLK_EN_V              0x1u
#define PMU_EXT_LDO_P1_0P1A_REG                      0x501151d0u
#define PMU_0P1A_FORCE_TIEH_SEL_1_S                  7u
#define PMU_0P1A_FORCE_TIEH_SEL_1_V                  0x1u
#define PMU_0P1A_XPD_1_S                             8u
#define PMU_0P1A_XPD_1_V                             0x1u
#define PMU_0P1A_TIEH_SEL_1_S                        9u
#define PMU_0P1A_TIEH_SEL_1_V                        0x7u
#define PMU_0P1A_TIEH_1_S                            14u
#define PMU_0P1A_TIEH_1_V                            0x1u
#define PMU_EXT_LDO_P1_0P1A_ANA_REG                  0x501151d4u
#define PMU_ANA_0P1A_MUL_1_S                         23u
#define PMU_ANA_0P1A_MUL_1_V                         0x7u
#define PMU_ANA_0P1A_DREF_1_S                        28u
#define PMU_ANA_0P1A_DREF_1_V                        0xfu
#define IOMUX_MSPI_PIN_PSRAM_D_PIN0_REG              0x500e121cu
#define IOMUX_MSPI_PIN_REG_PSRAM_D_DRV_S             12u
#define IOMUX_MSPI_PIN_REG_PSRAM_D_DRV_V             0x3u
#define IOMUX_MSPI_PIN_PSRAM_Q_PIN0_REG              0x500e1220u
#define IOMUX_MSPI_PIN_REG_PSRAM_Q_DRV_S             12u
#define IOMUX_MSPI_PIN_REG_PSRAM_Q_DRV_V             0x3u
#define IOMUX_MSPI_PIN_PSRAM_WP_PIN0_REG             0x500e1224u
#define IOMUX_MSPI_PIN_REG_PSRAM_WP_DRV_S            12u
#define IOMUX_MSPI_PIN_REG_PSRAM_WP_DRV_V            0x3u
#define IOMUX_MSPI_PIN_PSRAM_HOLD_PIN0_REG           0x500e1228u
#define IOMUX_MSPI_PIN_REG_PSRAM_HOLD_DRV_S          12u
#define IOMUX_MSPI_PIN_REG_PSRAM_HOLD_DRV_V          0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ4_PIN0_REG            0x500e122cu
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ4_DRV_S           12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ4_DRV_V           0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ5_PIN0_REG            0x500e1230u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ5_DRV_S           12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ5_DRV_V           0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ6_PIN0_REG            0x500e1234u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ6_DRV_S           12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ6_DRV_V           0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ7_PIN0_REG            0x500e1238u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ7_DRV_S           12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ7_DRV_V           0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ8_PIN0_REG            0x500e1248u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ8_DRV_S           12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ8_DRV_V           0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ9_PIN0_REG            0x500e124cu
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ9_DRV_S           12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ9_DRV_V           0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ10_PIN0_REG           0x500e1250u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ10_DRV_S          12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ10_DRV_V          0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ11_PIN0_REG           0x500e1254u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ11_DRV_S          12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ11_DRV_V          0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ12_PIN0_REG           0x500e1258u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ12_DRV_S          12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ12_DRV_V          0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ13_PIN0_REG           0x500e125cu
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ13_DRV_S          12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ13_DRV_V          0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ14_PIN0_REG           0x500e1260u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ14_DRV_S          12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ14_DRV_V          0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQ15_PIN0_REG           0x500e1264u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ15_DRV_S          12u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQ15_DRV_V          0x3u
#define IOMUX_MSPI_PIN_PSRAM_CK_PIN0_REG             0x500e1240u
#define IOMUX_MSPI_PIN_REG_PSRAM_CK_DRV_S            12u
#define IOMUX_MSPI_PIN_REG_PSRAM_CK_DRV_V            0x3u
#define IOMUX_MSPI_PIN_PSRAM_CS_PIN0_REG             0x500e1244u
#define IOMUX_MSPI_PIN_REG_PSRAM_CS_DRV_S            12u
#define IOMUX_MSPI_PIN_REG_PSRAM_CS_DRV_V            0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQS_0_PIN0_REG          0x500e123cu
#define IOMUX_MSPI_PIN_REG_PSRAM_DQS_0_XPD_S         0u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQS_0_XPD_V         0x1u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQS_0_DRV_S         15u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQS_0_DRV_V         0x3u
#define IOMUX_MSPI_PIN_PSRAM_DQS_1_PIN0_REG          0x500e1268u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQS_1_XPD_S         0u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQS_1_XPD_V         0x1u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQS_1_DRV_S         15u
#define IOMUX_MSPI_PIN_REG_PSRAM_DQS_1_DRV_V         0x3u

#endif
