#ifndef LUGALOS_DRIVERS_FONT8X16_H
#define LUGALOS_DRIVERS_FONT8X16_H

#include <stdint.h>

#include "drivers/lcdterm_attr.h"   /* the tables live where the lcdterm task can read them */

/* 36.5, plan/phase36_rp2350_lcd7_terminal.md §4.2: Spleen 8x16 (BSD 2-Clause,
 * tools/fonts/LICENSE.spleen), generated by tools/gen_font_bdf.py into
 * drivers/font8x16.c. One byte per glyph row with the leftmost pixel in bit 0
 * -- the RP2350-LCD-7 framebuffer's order, so a row is stored with a single
 * byte write.
 *
 * 37.1, plan/phase37_screen_layouts_and_apps.md §3.1: indexed by the
 * terminal's **internal glyph code** (minus FONT8X16_FIRST), one byte per
 * cell, which is what the cell shadow stores:
 *   0x20..0x7E  ASCII
 *   0x7F        the replacement glyph, for anything the font cannot draw
 *   0x80..0x9F  box drawing, chess figurines, euro, quotes, blocks
 *               (font8x16_map_cp/_code below)
 *   0xA0..0xFF  Latin-1, at the same numbers as their code points */
#define FONT8X16_FIRST        0x20
#define FONT8X16_LAST         0xff
#define FONT8X16_REPLACEMENT  0x7f
#define FONT8X16_W            8
#define FONT8X16_H            16

extern const uint8_t font8x16_glyphs[FONT8X16_LAST - FONT8X16_FIRST + 1][FONT8X16_H];

/* The code points at 0x80..0x9F, sorted, with their glyph codes. */
#define FONT8X16_MAP_COUNT 32
extern const uint16_t font8x16_map_cp[FONT8X16_MAP_COUNT];
extern const uint8_t font8x16_map_code[FONT8X16_MAP_COUNT];

#endif /* LUGALOS_DRIVERS_FONT8X16_H */
