#ifndef LUGALOS_DRIVERS_FONT8X16_H
#define LUGALOS_DRIVERS_FONT8X16_H

#include <stdint.h>

/* 36.5, plan/phase36_rp2350_lcd7_terminal.md §4.2: Spleen 8x16 (BSD 2-Clause,
 * tools/fonts/LICENSE.spleen), printable ASCII only, generated by
 * tools/gen_font_bdf.py into drivers/font8x16.c. One byte per glyph row with
 * the leftmost pixel in bit 0 -- the RP2350-LCD-7 framebuffer's order, so a
 * row is stored with a single byte write. */
#define FONT8X16_FIRST  0x20
#define FONT8X16_LAST   0x7e
#define FONT8X16_W      8
#define FONT8X16_H      16

extern const uint8_t font8x16_glyphs[FONT8X16_LAST - FONT8X16_FIRST + 1][FONT8X16_H];

/* 36.6: the few code points beyond ASCII this tree prints (box drawing for
 * the `e` editor's frame), sorted, with their glyphs in the same order. */
#define FONT8X16_EXTRA_COUNT 11
extern const uint16_t font8x16_extra_cp[FONT8X16_EXTRA_COUNT];
extern const uint8_t font8x16_extra[FONT8X16_EXTRA_COUNT][FONT8X16_H];

#endif /* LUGALOS_DRIVERS_FONT8X16_H */
