#!/usr/bin/env python3
"""45.6, plan/phase45_esp32c6.md: prepare Espressif's Wi-Fi archives for linking
into a kernel that has its own libc.

The blob calls memcpy, memset, strlen... by name. In this image those names are
the *kernel's*: functions in kernel text, which the radio's U-mode domain cannot
execute -- and the chip-ROM symbol scripts that would give the blob the ROM's
copies silently *replace* the kernel's definitions of the same names instead
(a script assignment overrides an object's symbol), which would quietly move the
whole kernel onto the ROM's libc. Neither is wanted.

So the blob's imports are made explicit. Every symbol the archives leave
undefined that the ROM provides, or that the radio's own libc
(drivers/radio/radio_libc.c) defines, is renamed `radio_<name>` -- in the copies
of the archives this writes, never in Espressif's. The ROM ones are then
*assigned* by a generated script (`radio_<name> = <ROM address>`); the others
are radio_libc.c's `radio_<name>`. The kernel's libc is never involved, and the
kernel's own calls are untouched.

Usage: c6_radio_libs.py OUT_DIR ROM_LD_DIR ARCHIVE...
Writes OUT_DIR/<archive>, OUT_DIR/radio_rom.ld and OUT_DIR/rename.txt.
"""
import os
import re
import subprocess
import sys

# What drivers/radio/radio_libc.c defines (as radio_<name>).
RADIO_LIBC = ["memcpy", "memmove", "memcmp", "strcpy", "strncpy", "strncmp", "free", "sprintf",
              "puts", "putchar", "floor", "hexstr2bin", "pp_printf", "phy_printf",
              "net80211_printf", "coexist_printf", "rtc_clk_xtal_freq_get"]
# ROM functions the radio's own code (not the blob) calls, declared in C with an
# asm label of the radio_ name: they get their ROM address here like the rest.
EXTRA_ROM = ["ets_update_cpu_frequency", "ets_delay_us", "memset", "ets_install_putc1", "ets_install_putc2"]
ROM_SCRIPTS = ["rom", "rom.pp", "rom.net80211", "rom.phy", "rom.coexist", "rom.libc",
               "rom.newlib", "rom.libgcc", "rom.api"]
NM = "riscv64-elf-nm"
OBJCOPY = "riscv64-elf-objcopy"


def tool(name):
    for cand in (name, name.replace("riscv64-elf", "riscv64-unknown-elf")):
        if subprocess.run(["which", cand], capture_output=True).returncode == 0:
            return cand
    sys.exit("no %s on PATH" % name)


def main():
    out, rom_dir, archives = sys.argv[1], sys.argv[2], sys.argv[3:]
    nm, objcopy = tool(NM), tool(OBJCOPY)
    os.makedirs(out, exist_ok=True)

    rom = {}
    for f in ROM_SCRIPTS:
        for line in open(os.path.join(rom_dir, "esp32c6.%s.ld" % f)):
            m = re.match(r"\s*(\w+)\s*=\s*(0x[0-9a-fA-F]+)\s*;", line)
            if m:
                rom.setdefault(m.group(1), m.group(2))

    undef, defined = set(), set()
    for a in archives:
        for line in subprocess.run([nm, "-A", a], capture_output=True, text=True).stdout.splitlines():
            parts = line.split()
            if len(parts) >= 3 and parts[-2] == "U":
                undef.add(parts[-1])
            elif len(parts) >= 3 and parts[-2] in "TtDdBbRrSsWwVvCc":
                defined.add(parts[-1])
    undef -= defined          # resolved inside the group: not an import
    undef |= set(EXTRA_ROM)

    renamed = {}
    for s in sorted(undef):
        if s in rom or s in RADIO_LIBC:
            renamed[s] = "radio_" + s

    with open(os.path.join(out, "rename.txt"), "w") as f:
        for s, r in renamed.items():
            f.write("%s %s\n" % (s, r))
    # The 64-bit and bit-twiddling helpers libgcc provides on rv32. Compiled code in the radio's domain
    # (the supplicant: time arithmetic) calls them by name, and the kernel's copy is in kernel text;
    # the ROM has its own. Assigned *unrenamed*: every caller, the kernel's included, gets the ROM's
    # (correct in M-mode too), and the libgcc archive member is never pulled.
    GCC_HELPERS = ["__divdi3", "__udivdi3", "__moddi3", "__umoddi3", "__ashldi3", "__lshrdi3",
                   "__ashrdi3", "__muldi3", "__clzsi2", "__ctzsi2", "__popcountsi2", "__bswapsi2"]
    with open(os.path.join(out, "radio_rom.ld"), "w") as f:
        # Peripheral register blocks IDF's headers name as objects (esp32c6.peripherals.ld).
        f.write("MODEM_LPCON = 0x600AF000;\nMODEM_SYSCON = 0x600A9800;\nEFUSE = 0x600B0800;\nPMU = 0x600B0000;\nLP_CLKRST = 0x600B0400;\nPCR = 0x60096000;\n")
        for h in GCC_HELPERS:
            if h in rom and h != "__bswapsi2":
                f.write("%s = %s;\n" % (h, rom[h]))
        f.write("/* generated by tools/c6_radio_libs.py: the blob's ROM imports, under their radio_ names */\n")
        for s, r in renamed.items():
            if s in rom and s not in RADIO_LIBC:
                f.write("%s = %s;\n" % (r, rom[s]))
    for a in archives:
        subprocess.run([objcopy, "--redefine-syms", os.path.join(out, "rename.txt"), a,
                        os.path.join(out, os.path.basename(a))], check=True)
    n_rom = sum(1 for s in renamed if s in rom and s not in RADIO_LIBC)
    print("c6_radio_libs: %d imports from the ROM, %d from radio_libc, %d archives" %
          (n_rom, sum(1 for s in renamed if s in RADIO_LIBC), len(archives)))


if __name__ == "__main__":
    main()
