#!/usr/bin/env python3
"""
embed_cyw43_fw.py - CYW43439 firmware blob embedder for LugalOS.

Turns the three binaries in firmware/cyw43/ into one compiled C file, the
same way create_flash_fs.py turns a staged directory into flash_fs.c. The
wireless chip has no flash of its own, so all three have to live in our
image and be uploaded over gSPI at every boot (R5,
plan/phase19_ip_stack_and_ethernet.md).

Provenance and licence for the blobs themselves are in
firmware/cyw43/README.md -- read that before updating them.

Usage: embed_cyw43_fw.py <output.c> <firmware-dir>
"""

import sys
from pathlib import Path

# name in firmware/cyw43/  ->  C symbol base
BLOBS = [
    ("43439A0.bin", "cyw43_fw"),
    ("43439A0_clm.bin", "cyw43_clm"),
    ("nvram_rp2040.bin", "cyw43_nvram"),
]


def emit_array(out, data: bytes, symbol: str) -> None:
    # 4-byte aligned because the driver hands these straight to a
    # backplane write that packs them into 32-bit words.
    out.write(
        "const uint8_t %s[%d] __attribute__((aligned(4))) = {\n" % (symbol, len(data))
    )
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        out.write("    " + ", ".join("0x%02x" % b for b in chunk) + ",\n")
    out.write("};\n")
    out.write("const unsigned %s_len = %d;\n\n" % (symbol, len(data)))


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_cyw43_fw.py <output.c> <firmware-dir>", file=sys.stderr)
        return 2

    out_path = Path(sys.argv[1])
    fw_dir = Path(sys.argv[2])

    blobs = []
    for filename, symbol in BLOBS:
        path = fw_dir / filename
        if not path.exists():
            print(
                "[CYW43] missing blob: %s\n"
                "        See firmware/cyw43/README.md for where these come from."
                % path,
                file=sys.stderr,
            )
            return 1
        blobs.append((symbol, path.read_bytes()))

    total = sum(len(d) for _, d in blobs)
    print(
        "[CYW43] Embedding %d bytes of wireless firmware (%s) into '%s'..."
        % (total, ", ".join("%s=%d" % (s, len(d)) for s, d in blobs), out_path)
    )

    with open(out_path, "w") as out:
        out.write(
            "/* Auto-generated by tools/embed_cyw43_fw.py -- do not edit.\n"
            " *\n"
            " * Infineon CYW43439 firmware, CLM regulatory data and NVRAM.\n"
            " * These are the only non-source artifacts in a LugalOS image;\n"
            " * provenance, sizes and the Infineon Permissive Binary License\n"
            " * they ship under are documented in firmware/cyw43/README.md.\n"
            " */\n"
            "#include <stdint.h>\n\n"
        )
        for symbol, data in blobs:
            emit_array(out, data, symbol)

    return 0


if __name__ == "__main__":
    sys.exit(main())
