#!/usr/bin/env python3
"""Regenerates user/chess/include/zobrist_tables.h.

The Zobrist keys are the output of a fixed xorshift PRNG with a fixed seed
(the engine's own, vendored from ~/gith/domschl/LugalChess) -- 849 numbers that
have never changed and cannot, without changing how positions hash. Section 3.2
of plan/phase15_memory_reclamation.md moved them out of .bss, where they cost
6.8 KB of an RP2350's RAM from boot, into flash as const data.

This script exists so the table is reproducible rather than magic: run it and
`git diff` should be empty. It is deliberately NOT wired into the build --
regenerating a constant on every compile would only create a way for it to
change by accident.

    python3 tools/gen_zobrist.py
"""

import pathlib

MASK = (1 << 64) - 1
OUT = (pathlib.Path(__file__).resolve().parent.parent
       / "user" / "chess" / "include" / "zobrist_tables.h")

_state = 1802


def prng_next() -> int:
    """user/chess/src/zobrist.c's prng_next(), exactly."""
    global _state
    _state ^= _state >> 12
    _state &= MASK
    _state ^= (_state << 25) & MASK
    _state &= MASK
    _state ^= _state >> 27
    _state &= MASK
    return (_state * 2685821657736338717) & MASK


def rows(values, indent):
    for i in range(0, len(values), 4):
        yield indent + " ".join("0x%016xULL," % v for v in values[i:i + 4])


def main() -> int:
    # Order matters: this is init_zobrist()'s own draw order, and changing it
    # changes every key.
    pieces = [[[prng_next() for _ in range(64)] for _ in range(2)] for _ in range(6)]
    castling = [prng_next() for _ in range(16)]
    en_passant = [prng_next() for _ in range(64)]
    side = prng_next()

    L = [
        "/* GENERATED by tools/gen_zobrist.py -- do not edit by hand.",
        " *",
        " * The Zobrist hash keys, precomputed. They used to be filled at every",
        " * chess session start by init_zobrist(), into 6.8 KB of .bss; on RP2350",
        " * .bss and the heap are the same budget, so that was 6.8 KB of heap held",
        " * against a table whose contents are a mathematical constant. See",
        " * plan/phase15_memory_reclamation.md, section 3.2.",
        " *",
        " * Measured before committing to flash rather than assumed: perft on real",
        " * RP2350 silicon runs 188.6K nps with these in flash against 185.5K with",
        " * the same tables in .bss -- no regression, marginally faster. The XIP",
        " * cache holds a table this size comfortably across the repeated random",
        " * reads a search makes of it.",
        " *",
        " * Reproducible: rerun the generator and `git diff` should be empty. */",
        "#ifndef LUGALOS_CHESS_ZOBRIST_TABLES_H",
        "#define LUGALOS_CHESS_ZOBRIST_TABLES_H",
        "",
        "#include <stdint.h>",
        "",
        "static const uint64_t zobrist_pieces_flash[6][2][64] = {",
    ]
    for p in range(6):
        L.append("  {")
        for c in range(2):
            L.append("    {")
            L.extend(rows(pieces[p][c], "      "))
            L.append("    },")
        L.append("  },")
    L += ["};", ""]

    L.append("static const uint64_t zobrist_castling_flash[16] = {")
    L.extend(rows(castling, "  "))
    L += ["};", ""]

    L.append("static const uint64_t zobrist_en_passant_flash[64] = {")
    L.extend(rows(en_passant, "  "))
    L += ["};", ""]

    L.append("static const uint64_t zobrist_side_flash = 0x%016xULL;" % side)
    L += ["", "#endif /* LUGALOS_CHESS_ZOBRIST_TABLES_H */"]

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
