#!/usr/bin/env python3
"""gen_font_bdf.py - a fixed-cell BDF font as a C table for the 1-bpp screen.

    python3 tools/gen_font_bdf.py tools/fonts/spleen-8x16.bdf drivers/font8x16.c

36.5, plan/phase36_rp2350_lcd7_terminal.md §4.2. Emits the printable ASCII
range (0x20..0x7E) as `font8x16_glyphs[95][16]`, one byte per glyph row.

**The bit order is decided here, once, and nowhere else.** The RP2350-LCD-7's
pixel state machine shifts its framebuffer words out to the right, so the
leftmost pixel of a byte is its *least* significant bit (drivers/lcd7.h). BDF
stores the leftmost pixel in the *most* significant bit. So every row is
bit-reversed on the way out, and a glyph row can then be stored into the
framebuffer as a single byte with no work at runtime.

The font's own copyright notice and licence are carried into the generated
file's header, as the BSD licence requires of a source redistribution.
"""

import os
import sys

FIRST, LAST = 0x20, 0x7E
CELL_W, CELL_H = 8, 16


def reverse8(b: int) -> int:
    return int(f"{b:08b}"[::-1], 2)


def parse(path: str) -> tuple[list[str], dict[int, list[int]]]:
    notice: list[str] = []
    glyphs: dict[int, list[int]] = {}
    enc = None
    bbx = None
    rows: list[int] | None = None
    ascent = descent = None
    with open(path, encoding="ascii") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("COMMENT"):
                notice.append(line[len("COMMENT"):].strip())
            elif line.startswith("FONT_ASCENT"):
                ascent = int(line.split()[1])
            elif line.startswith("FONT_DESCENT"):
                descent = int(line.split()[1])
            elif line.startswith("ENCODING"):
                enc = int(line.split()[1])
            elif line.startswith("BBX"):
                bbx = tuple(int(v) for v in line.split()[1:])
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                if enc is not None and FIRST <= enc <= LAST:
                    if bbx != (CELL_W, CELL_H, 0, -(descent or 0)):
                        sys.exit(f"glyph {enc:#x}: BBX {bbx} is not the full {CELL_W}x{CELL_H} cell; "
                                 "this generator only handles fixed-cell fonts")
                    glyphs[enc] = rows or []
                enc, bbx, rows = None, None, None
            elif rows is not None:
                rows.append(int(line, 16))
    if ascent is None or descent is None or ascent + descent != CELL_H:
        sys.exit(f"FONT_ASCENT + FONT_DESCENT must be {CELL_H}")
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        sys.exit(f"missing glyphs: {', '.join(hex(c) for c in missing)}")
    return notice, glyphs


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, out = sys.argv[1], sys.argv[2]
    notice, glyphs = parse(src)
    with open(out, "w", encoding="ascii") as f:
        f.write("/* Generated by tools/gen_font_bdf.py -- do not edit.\n")
        f.write(f" *\n *   python3 tools/gen_font_bdf.py {src} {out}\n *\n")
        f.write(" * Printable ASCII (0x20..0x7E), 8x16 cells, one byte per row, **leftmost\n")
        f.write(" * pixel in bit 0** (bit-reversed from BDF; see the generator for why).\n")
        f.write(" *\n * The font's own notice, from the BDF, followed by its licence (BSD\n")
        f.write(" * 2-Clause, tools/fonts/LICENSE.spleen):\n *\n")
        for line in notice:
            if line in ("/*", "*/"):
                continue
            text = line.lstrip("*").strip()
            f.write(f" *   {text}\n" if text else " *\n")
        # The licence's full text, not only the notice: a BSD source
        # redistribution must retain the conditions and the disclaimer too.
        lic = os.path.join(os.path.dirname(src), "LICENSE.spleen")
        if os.path.exists(lic):
            f.write(" *\n *   ---- tools/fonts/LICENSE.spleen ----\n")
            with open(lic, encoding="utf-8") as lf:
                for text in lf.read().splitlines():
                    f.write(f" *   {text}".rstrip() + "\n")
        f.write(" */\n\n#include \"drivers/font8x16.h\"\n\n")
        f.write(f"const uint8_t font8x16_glyphs[{LAST - FIRST + 1}][{CELL_H}] = {{\n")
        for c in range(FIRST, LAST + 1):
            label = chr(c) if chr(c) not in "\\'" else "\\" + chr(c)
            data = ", ".join(f"0x{reverse8(r):02x}" for r in glyphs[c])
            f.write(f"    /* 0x{c:02x} '{label}' */ {{ {data} }},\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
