#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.9"
# dependencies = ["esptool"]
# ///
"""Write the LugalOS filesystem image to the ESP32-P4-NANO's flash.

E6, plan/phase27_esp32p4_bringup.md. The counterpart to tools/p4run.py, which
loads the *kernel* into RAM and never touches flash.

## Two images, flashed independently

README.md's "Two images, flashed independently" is an RP2350 story about two
UF2 files. The same split holds here for the same reason -- the filesystem
changes almost never and the kernel changes constantly -- but the mechanism is
different in a way worth stating: on this board the kernel is not flashed at
all. It is delivered into L2MEM by `esptool load-ram` on every run, so there
is exactly one thing in flash, and it is the filesystem.

## Why this takes no address argument

The base address comes from build/esp32p4/flashfs.addr, generated by CMake
from cmake/flash_layout_esp32p4.cmake -- the same single definition the kernel
was compiled against. An address typed on a command line is one that can
disagree with the kernel's, and the symptom of that disagreement is a
filesystem that mounts as garbage rather than an error.

## What this will not do

The write is bounded to the region the layout declares, and refuses anything
below it. The board's Waveshare factory image occupies the low 13.06 MB and is
not obtainable again once overwritten; the segment starts at 14 MB, and the
~0.9 MB between them is deliberate margin. A verified backup lives at
~/gith/esp/p4nano-factory-flash/ and the restore command is in its README --
but nothing this script does should ever need it.
"""

import argparse
import pathlib
import subprocess
import sys

DEFAULT_BUILD = pathlib.Path(__file__).resolve().parent.parent / "build" / "esp32p4"
# The floor, duplicated here on purpose: this script is the one thing that can
# write flash without the kernel's guard in front of it, so it carries its own
# rather than trusting the file it just read.
FACTORY_TOP = 0x00D10000


def read_layout(build: pathlib.Path):
    f = build / "flashfs.addr"
    if not f.exists():
        sys.exit("%s not found -- build the esp32p4 preset first" % f)
    base_s, size_s = f.read_text().split()
    return int(base_s, 0), int(size_s, 0)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--build", type=pathlib.Path, default=DEFAULT_BUILD)
    ap.add_argument("--port", help="console port (esptool talks over this)")
    ap.add_argument("--reset-port", help="port whose DTR/RTS reach the board's reset")
    ap.add_argument("--baud", type=int, default=921600)
    ap.add_argument("--verify", action="store_true",
                    help="re-verify with esptool's on-chip digest afterwards")
    a = ap.parse_args()

    base, size = read_layout(a.build)
    img = a.build / "flashfs.bin"
    if not img.exists():
        sys.exit("%s not found -- build the esp32p4 preset first" % img)

    actual = img.stat().st_size
    if actual != size:
        sys.exit("flashfs.bin is %d bytes but the layout reserves %d; "
                 "they must match or the tail of the region is stale"
                 % (actual, size))
    if base < FACTORY_TOP:
        sys.exit("refusing: 0x%06x is inside the factory image (ends 0x%06x)"
                 % (base, FACTORY_TOP))

    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    import p4run  # ports and reset live there; one implementation, not two
    port = a.port or p4run.console_port(None)
    rport = a.reset_port or p4run.reset_port(None, port)

    # Into download mode first, and this is not optional: a board running the
    # kernel is writing to UART0 continuously, and esptool reports that as
    # "Invalid head of packet (0x1B): Possible serial noise or corruption" --
    # which reads like a cabling fault and is actually just a program doing
    # its job. The reset lines are on a different cable here than the console
    # (see tests/hw/README.md); p4run works out both.
    print("resetting %s into download mode via %s" % (port, rport))
    p4run.enter_download(rport)

    print("flashing %s (%d bytes) to 0x%06x on %s" % (img.name, actual, base, port))
    cmd = ["esptool", "--chip", "esp32p4", "--port", port, "--baud", str(a.baud),
           "write-flash", hex(base), str(img)]
    rc = subprocess.call(cmd)
    if rc != 0:
        return rc

    if a.verify:
        # esptool hard-resets out of download mode when write-flash finishes,
        # so the board has to be put back before it can be asked anything
        # else. Without this the verify pass fails with "No serial data
        # received", which looks like the write went wrong and means the
        # opposite -- it finished and the board rebooted.
        p4run.enter_download(rport)
        # An on-chip digest, not a re-read: a re-read can reproduce its own
        # transfer bug and look like agreement. Same reasoning the factory
        # backup's README records for how that image was verified.
        rc = subprocess.call(["esptool", "--chip", "esp32p4", "--port", port,
                              "--baud", str(a.baud), "verify-flash",
                              hex(base), str(img)])
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
