#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.9"
# dependencies = ["esptool"]
# ///
"""Write the LugalOS filesystem image to the ESP32-P4-NANO's flash.

E6, plan/phase27_esp32p4_bringup.md. The counterpart to tools/p4run.py, which
loads the *kernel* into RAM and never touches flash.

## Two images, flashed independently

README.md's "Two images, flashed independently" is an RP2350 story about two
UF2 files. The same split holds here for the same reason -- the filesystem
changes almost never and the kernel changes constantly -- but the mechanism is
different in a way worth stating: on this board the kernel is not flashed at
all. It is delivered into L2MEM by `esptool load-ram` on every run, so there
is exactly one thing in flash, and it is the filesystem.

## Why this takes no address argument

The base address comes from build/esp32p4/flashfs.addr, generated by CMake
from cmake/flash_layout_esp32p4.cmake -- the same single definition the kernel
was compiled against. An address typed on a command line is one that can
disagree with the kernel's, and the symptom of that disagreement is a
filesystem that mounts as garbage rather than an error.

## What this will not do

The write is bounded to the region the layout declares, and refuses anything
below the writable floor.

Until phase 32 that floor protected the Waveshare factory image, which
occupied the low 13.06 MB and is not obtainable again once overwritten. U0
retired that image on purpose -- LugalOS owns all 16 MB now, and the boot ROM
reads its second-stage image from 0x2000, which is inside what the factory
occupied. The verified backup at ~/gith/esp/p4nano-factory-flash/ remains, and
its README has the restore command.

So the floor now protects what actually must not be damaged by a filesystem
write: **the second-stage bootloader and the OS image executed in place from
flash**. Overwriting either leaves a board that does not boot -- recoverable
through the ROM's download mode (`p4run.py --reset-test` proves that path
works on this host), but a recovery rather than a mistake absorbed.

The floor is duplicated here rather than read from the layout, on purpose:
this script is the one thing that writes flash without the kernel's own guard
in front of it, so it carries its own copy and a layout edit alone cannot
widen what it will overwrite.
"""

import argparse
import pathlib
import subprocess
import sys

DEFAULT_BUILD = pathlib.Path(__file__).resolve().parent.parent / "build" / "esp32p4"
# The floor, duplicated here on purpose -- see the module docstring. This must
# match LUGALOS_P4_FLASH_WRITABLE_FLOOR in cmake/flash_layout_esp32p4.cmake;
# they are deliberately two copies of one number, so that changing the layout
# does not silently change what this script is willing to destroy.
WRITABLE_FLOOR = 0x00110000


def read_layout(build: pathlib.Path):
    f = build / "flashfs.addr"
    if not f.exists():
        sys.exit("%s not found -- build the esp32p4 preset first" % f)
    base_s, size_s = f.read_text().split()
    return int(base_s, 0), int(size_s, 0)


def read_segments(build: pathlib.Path):
    """The whole flash map, as the build generated it.

    U0/U2, plan/phase32_esp32p4_execute_in_place.md. Each line is
    `name base reserved artifact fit|exact`:

      boot  the ROM's second-stage image, at the offset the ROM insists on
      os    .text + .rodata, mapped into the XIP window at run time
      fs    the FAT32 filesystem

    `exact` means the artifact must fill its region -- true of the filesystem,
    whose tail would otherwise be whatever was there before. `fit` means it
    only has to be no larger, which is what a code segment with growth room
    needs."""
    f = build / "flash_segments.txt"
    if not f.exists():
        sys.exit("%s not found -- build the esp32p4 preset first" % f)
    segs = []
    for line in f.read_text().split("\n"):
        if not line.strip():
            continue
        name, base, size, artifact, mode = line.split()
        segs.append((name, int(base, 0), int(size, 0), artifact, mode))
    return segs


def make_boot_image(build: pathlib.Path):
    """Turn the RAM half into the image the ROM can boot.

    The build emits lugalos-ram.elf -- the loadable sections that stay in
    L2MEM, with the flash-resident ones removed -- and the ROM wants an ESP
    image: segments with load addresses, a header and a checksum. `elf2image`
    is what produces that, and it lives here rather than in CMake because
    esptool is this script's dependency and not the build's."""
    elf = build / "lugalos-ram.elf"
    if not elf.exists():
        sys.exit("%s not found -- build the esp32p4 preset first" % elf)
    img = build / "lugalos-boot.img"
    rc = subprocess.call(["esptool", "--chip", "esp32p4", "elf2image",
                          "-o", str(img), str(elf)])
    if rc != 0:
        sys.exit("elf2image failed on %s" % elf.name)
    return img


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--build", type=pathlib.Path, default=DEFAULT_BUILD)
    ap.add_argument("--port", help="console port (esptool talks over this)")
    ap.add_argument("--reset-port", help="port whose DTR/RTS reach the board's reset")
    ap.add_argument("--baud", type=int, default=921600)
    ap.add_argument("--only", help="comma-separated segments to write "
                    "(boot,os,fs); default all three")
    ap.add_argument("--verify", action="store_true",
                    help="re-verify with esptool's on-chip digest afterwards")
    a = ap.parse_args()

    segs = read_segments(a.build)
    wanted = set(a.only.split(",")) if a.only else {n for n, *_ in segs}
    unknown = wanted - {n for n, *_ in segs}
    if unknown:
        sys.exit("no such segment: %s (have: %s)"
                 % (", ".join(sorted(unknown)), ", ".join(n for n, *_ in segs)))

    # The boot image is generated rather than built, so make it before any
    # sizes are checked.
    if "boot" in wanted:
        make_boot_image(a.build)

    plan = []
    for name, base, size, artifact, mode in segs:
        if name not in wanted:
            continue
        img = a.build / artifact
        if not img.exists():
            sys.exit("%s not found -- build the esp32p4 preset first" % img)
        actual = img.stat().st_size
        if mode == "exact" and actual != size:
            sys.exit("%s is %d bytes but the layout reserves %d; they must "
                     "match or the tail of the region is stale"
                     % (artifact, actual, size))
        if actual > size:
            sys.exit("%s is %d bytes and does not fit the %d reserved for "
                     "'%s'; raise it in cmake/flash_layout_esp32p4.cmake"
                     % (artifact, actual, size, name))
        # The floor protects the bootloader and the OS image from a
        # *filesystem* write. Writing those segments deliberately is this
        # script's job, so the check applies to what the kernel may touch at
        # run time -- the filesystem -- and not to a deliberate reflash.
        if name == "fs" and base < WRITABLE_FLOOR:
            sys.exit("refusing: 0x%06x is below the writable floor (0x%06x) "
                     "-- the bootloader and the OS image live there"
                     % (base, WRITABLE_FLOOR))
        plan.append((name, base, img, actual))

    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    import p4run  # ports and reset live there; one implementation, not two
    port = a.port or p4run.console_port(None)
    rport = a.reset_port or p4run.reset_port(None, port)

    # Into download mode first, and this is not optional: a board running the
    # kernel is writing to UART0 continuously, and esptool reports that as
    # "Invalid head of packet (0x1B): Possible serial noise or corruption" --
    # which reads like a cabling fault and is actually just a program doing
    # its job. The reset lines are on a different cable here than the console
    # (see tests/hw/README.md); p4run works out both.
    print("resetting %s into download mode via %s" % (port, rport))
    p4run.enter_download(rport)

    # One esptool invocation for every segment, so the board enters download
    # mode once and the writes cannot be interleaved with a reset.
    cmd = ["esptool", "--chip", "esp32p4", "--port", port, "--baud",
           str(a.baud), "write-flash"]
    for name, base, img, actual in plan:
        print("  %-4s %8d bytes -> 0x%06x  (%s)" % (name, actual, base, img.name))
        cmd += [hex(base), str(img)]
    rc = subprocess.call(cmd)
    if rc != 0:
        return rc

    if a.verify:
        # esptool hard-resets out of download mode when write-flash finishes,
        # so the board has to be put back before it can be asked anything
        # else. Without this the verify pass fails with "No serial data
        # received", which looks like the write went wrong and means the
        # opposite -- it finished and the board rebooted.
        p4run.enter_download(rport)
        # An on-chip digest, not a re-read: a re-read can reproduce its own
        # transfer bug and look like agreement. Same reasoning the factory
        # backup's README records for how that image was verified.
        vcmd = ["esptool", "--chip", "esp32p4", "--port", port, "--baud",
                str(a.baud), "verify-flash"]
        for name, base, img, actual in plan:
            vcmd += [hex(base), str(img)]
        rc = subprocess.call(vcmd)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
