# Generates lugalos_config.h from a per-board cmake/board-*.cmake file (K0,
# plan/phase7_kernel_config.md).
#
# Run as a build-time step (not just at configure time), same shape as
# gen_build_id.cmake, so an edited board file is picked up without a
# re-configure. The file is only rewritten when its contents change, so an
# unchanged config does not force a rebuild.
#
# The *schema* -- which CONFIG_* keys exist, and which are mandatory -- lives
# here, not in the board files. That keeps each board file a flat, diffable
# list of facts ("is this number right") rather than something that also has
# to get the shape right.
#
# Inputs: BOARD (path to the board-*.cmake file), OUT (header path to write),
# ENABLE_CC / ENABLE_ED / ENABLE_ST7735 / ENABLE_TM1638 / ENABLE_CHESS /
# ENABLE_SPISD / ENABLE_PICO_CLOCK_GREEN / ENABLE_DCF77 (ON/OFF feature
# flags, F0 plan/phase8_feature_flags.md, H3 plan/phase9_chess_computer.md,
# L1/L2 plan/phase11_pico_clock_green.md, D2 plan/phase17_clock_ui_and_
# dcf77.md -- build persona choices, not board facts, so they arrive as
# generator inputs rather than living in the board file). The last six are
# meaningful only on RP2350 (no display/keypad/chess/spisd/clockdisplay/
# dcf77 code path exists for any other target), but are still emitted
# everywhere for the same reason ENABLE_CC/
# ENABLE_ED are: the CMake option surface is uniform across targets, and a
# QEMU build carrying an inert CONFIG_ENABLE_ST7735 is harmless.

if(NOT DEFINED BOARD OR NOT EXISTS "${BOARD}")
    message(FATAL_ERROR "gen_config.cmake: board file not found: '${BOARD}'")
endif()
foreach(_flag ENABLE_CC ENABLE_ED ENABLE_ST7735 ENABLE_TM1638 ENABLE_CHESS ENABLE_SPISD ENABLE_PICO_CLOCK_GREEN ENABLE_DCF77)
    if(NOT DEFINED ${_flag})
        message(FATAL_ERROR "gen_config.cmake: ${_flag} is required")
    endif()
endforeach()

include("${BOARD}")

# Mandatory on every target that has a board file at all.
foreach(_key CONFIG_PALLOC_MAX_PAGES CONFIG_BALLOC_ARENA_PAGES CONFIG_UART0_BASE)
    if(NOT DEFINED ${_key})
        message(FATAL_ERROR "gen_config.cmake: ${BOARD} is missing required key ${_key}")
    endif()
endforeach()

foreach(_flag ENABLE_CC ENABLE_ED ENABLE_ST7735 ENABLE_TM1638 ENABLE_CHESS ENABLE_SPISD ENABLE_PICO_CLOCK_GREEN ENABLE_DCF77)
    if(${_flag})
        set(CONFIG_${_flag} 1)
    else()
        set(CONFIG_${_flag} 0)
    endif()
endforeach()

# Optional -- only a board with real GPIO pins to map (RP2350 today) sets
# these. Emitted if present, skipped otherwise: a QEMU target's virtio
# devices have no pins to describe.
set(_optional_keys
    CONFIG_UART0_TX_GPIO CONFIG_UART0_RX_GPIO
    CONFIG_SPI1_BASE CONFIG_SPI1_SCK_GPIO CONFIG_SPI1_MOSI_GPIO
    CONFIG_SPI1_MISO_GPIO CONFIG_SPI1_CS_GPIO
    CONFIG_LED_ONBOARD_GPIO CONFIG_LED_EXT_GPIO
    CONFIG_SPI0_BASE CONFIG_ST7735_SCK_GPIO CONFIG_ST7735_MOSI_GPIO
    CONFIG_ST7735_CS_GPIO CONFIG_ST7735_DC_GPIO CONFIG_ST7735_RST_GPIO
    CONFIG_TM1638_STB_GPIO CONFIG_TM1638_CLK_GPIO CONFIG_TM1638_DIO_GPIO
    CONFIG_CLOCK_OE_GPIO CONFIG_CLOCK_SDI_GPIO CONFIG_CLOCK_CLK_GPIO CONFIG_CLOCK_LE_GPIO
    CONFIG_CLOCK_A0_GPIO CONFIG_CLOCK_A1_GPIO CONFIG_CLOCK_A2_GPIO CONFIG_CLOCK_ADC_LIGHT_GPIO
    CONFIG_CLOCK_BTN_SET_GPIO CONFIG_CLOCK_BTN_UP_GPIO CONFIG_CLOCK_BTN_DOWN_GPIO
    CONFIG_CLOCK_BUZZER_GPIO
    CONFIG_CLOCK_TEMP_OFFSET_C CONFIG_CLOCK_COLON_BLINK CONFIG_CLOCK_BOOT_BEACON
    CONFIG_I2C_RTC_BASE CONFIG_I2C_RTC_SDA_GPIO CONFIG_I2C_RTC_SCL_GPIO
    # N3/N4/N5, plan/phase18_networking_and_auth.md: the gateway persona's
    # W5500 on SPI0 and its UART1 downlink. Optional like everything else
    # here -- a board without an Ethernet module simply does not set them.
    CONFIG_W5500_SCK_GPIO CONFIG_W5500_MOSI_GPIO CONFIG_W5500_MISO_GPIO
    CONFIG_W5500_CS_GPIO CONFIG_W5500_RST_GPIO CONFIG_W5500_INT_GPIO
    CONFIG_UART1_BASE CONFIG_UART1_TX_GPIO CONFIG_UART1_RX_GPIO
    CONFIG_DCF77_OUT_GPIO CONFIG_DCF77_PON_GPIO CONFIG_DCF77_PON_ACTIVE_LOW
    CONFIG_DCF77_OUT_ACTIVE_LOW
    CONFIG_DCF77_WARMUP_MS
    CONFIG_DCF77_PON_PRESENT
    CONFIG_DCF77_AUTO_HOUR CONFIG_DCF77_AUTO_MIN CONFIG_DCF77_AUTO_ENABLED
)

# Emitted as a quoted C string rather than a bare token, which is the only
# reason it needs its own list. A default is supplied here rather than in each
# board file because a timezone is not a board fact -- the same hardware works
# anywhere -- but every build needs one, and the kernel clock runs on UTC
# (kernel/timezone.h) so this only ever affects what a human is shown.
if(NOT DEFINED CONFIG_TIMEZONE)
    set(CONFIG_TIMEZONE "CET-1CEST,M3.5.0,M10.5.0/3")   # Europe/Berlin
endif()
set(_string_keys CONFIG_TIMEZONE)

set(_content "/* Generated by cmake/gen_config.cmake from ${BOARD} -- do not edit. */\n")
string(APPEND _content "#ifndef LUGALOS_CONFIG_H\n#define LUGALOS_CONFIG_H\n\n")
string(APPEND _content "#define CONFIG_PALLOC_MAX_PAGES ${CONFIG_PALLOC_MAX_PAGES}\n")
string(APPEND _content "#define CONFIG_BALLOC_ARENA_PAGES ${CONFIG_BALLOC_ARENA_PAGES}\n")
string(APPEND _content "#define CONFIG_UART0_BASE ${CONFIG_UART0_BASE}\n")
foreach(_flag ENABLE_CC ENABLE_ED ENABLE_ST7735 ENABLE_TM1638 ENABLE_CHESS ENABLE_SPISD ENABLE_PICO_CLOCK_GREEN ENABLE_DCF77)
    string(APPEND _content "#define CONFIG_${_flag} ${CONFIG_${_flag}}\n")
endforeach()
foreach(_key ${_optional_keys})
    if(DEFINED ${_key})
        string(APPEND _content "#define ${_key} ${${_key}}\n")
    endif()
endforeach()
foreach(_key ${_string_keys})
    string(APPEND _content "#define ${_key} \"${${_key}}\"\n")
endforeach()
string(APPEND _content "\n#endif /* LUGALOS_CONFIG_H */\n")

set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
