# Generates lugalos_config.h from a per-board cmake/board-*.cmake file (K0,
# plan/phase7_kernel_config.md).
#
# Run as a build-time step (not just at configure time), same shape as
# gen_build_id.cmake, so an edited board file is picked up without a
# re-configure. The file is only rewritten when its contents change, so an
# unchanged config does not force a rebuild.
#
# The *schema* -- which CONFIG_* keys exist, and which are mandatory -- lives
# here, not in the board files. That keeps each board file a flat, diffable
# list of facts ("is this number right") rather than something that also has
# to get the shape right.
#
# Inputs: BOARD (path to the board-*.cmake file), OUT (header path to write),
# ENABLE_CC / ENABLE_ED / ENABLE_ST7735 / ENABLE_TM1638 / ENABLE_CHESS /
# ENABLE_SPISD / ENABLE_PICO_CLOCK_GREEN (ON/OFF feature flags, F0
# plan/phase8_feature_flags.md, H3 plan/phase9_chess_computer.md, L1/L2
# plan/phase11_pico_clock_green.md -- build persona choices, not board
# facts, so they arrive as generator inputs rather than living in the
# board file). The last five are meaningful only on RP2350 (no
# display/keypad/chess/spisd/clockdisplay code path exists for any other
# target), but are still emitted everywhere for the same reason ENABLE_CC/
# ENABLE_ED are: the CMake option surface is uniform across targets, and a
# QEMU build carrying an inert CONFIG_ENABLE_ST7735 is harmless.

if(NOT DEFINED BOARD OR NOT EXISTS "${BOARD}")
    message(FATAL_ERROR "gen_config.cmake: board file not found: '${BOARD}'")
endif()
foreach(_flag ENABLE_CC ENABLE_ED ENABLE_ST7735 ENABLE_TM1638 ENABLE_CHESS ENABLE_SPISD ENABLE_PICO_CLOCK_GREEN)
    if(NOT DEFINED ${_flag})
        message(FATAL_ERROR "gen_config.cmake: ${_flag} is required")
    endif()
endforeach()

include("${BOARD}")

# Mandatory on every target that has a board file at all.
foreach(_key CONFIG_PALLOC_MAX_PAGES CONFIG_BALLOC_ARENA_PAGES CONFIG_UART0_BASE)
    if(NOT DEFINED ${_key})
        message(FATAL_ERROR "gen_config.cmake: ${BOARD} is missing required key ${_key}")
    endif()
endforeach()

foreach(_flag ENABLE_CC ENABLE_ED ENABLE_ST7735 ENABLE_TM1638 ENABLE_CHESS ENABLE_SPISD ENABLE_PICO_CLOCK_GREEN)
    if(${_flag})
        set(CONFIG_${_flag} 1)
    else()
        set(CONFIG_${_flag} 0)
    endif()
endforeach()

# Optional -- only a board with real GPIO pins to map (RP2350 today) sets
# these. Emitted if present, skipped otherwise: a QEMU target's virtio
# devices have no pins to describe.
set(_optional_keys
    CONFIG_UART0_TX_GPIO CONFIG_UART0_RX_GPIO
    CONFIG_SPI1_BASE CONFIG_SPI1_SCK_GPIO CONFIG_SPI1_MOSI_GPIO
    CONFIG_SPI1_MISO_GPIO CONFIG_SPI1_CS_GPIO
    CONFIG_LED_ONBOARD_GPIO CONFIG_LED_EXT_GPIO
    CONFIG_SPI0_BASE CONFIG_ST7735_SCK_GPIO CONFIG_ST7735_MOSI_GPIO
    CONFIG_ST7735_CS_GPIO CONFIG_ST7735_DC_GPIO CONFIG_ST7735_RST_GPIO
    CONFIG_TM1638_STB_GPIO CONFIG_TM1638_CLK_GPIO CONFIG_TM1638_DIO_GPIO
    CONFIG_CLOCK_OE_GPIO CONFIG_CLOCK_SDI_GPIO CONFIG_CLOCK_CLK_GPIO CONFIG_CLOCK_LE_GPIO
    CONFIG_CLOCK_A0_GPIO CONFIG_CLOCK_A1_GPIO CONFIG_CLOCK_A2_GPIO CONFIG_CLOCK_ADC_LIGHT_GPIO
    CONFIG_I2C_RTC_BASE CONFIG_I2C_RTC_SDA_GPIO CONFIG_I2C_RTC_SCL_GPIO
)

set(_content "/* Generated by cmake/gen_config.cmake from ${BOARD} -- do not edit. */\n")
string(APPEND _content "#ifndef LUGALOS_CONFIG_H\n#define LUGALOS_CONFIG_H\n\n")
string(APPEND _content "#define CONFIG_PALLOC_MAX_PAGES ${CONFIG_PALLOC_MAX_PAGES}\n")
string(APPEND _content "#define CONFIG_BALLOC_ARENA_PAGES ${CONFIG_BALLOC_ARENA_PAGES}\n")
string(APPEND _content "#define CONFIG_UART0_BASE ${CONFIG_UART0_BASE}\n")
foreach(_flag ENABLE_CC ENABLE_ED ENABLE_ST7735 ENABLE_TM1638 ENABLE_CHESS ENABLE_SPISD ENABLE_PICO_CLOCK_GREEN)
    string(APPEND _content "#define CONFIG_${_flag} ${CONFIG_${_flag}}\n")
endforeach()
foreach(_key ${_optional_keys})
    if(DEFINED ${_key})
        string(APPEND _content "#define ${_key} ${${_key}}\n")
    endif()
endforeach()
string(APPEND _content "\n#endif /* LUGALOS_CONFIG_H */\n")

set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
