# Generates lugalos_config.h from a per-board cmake/board-*.cmake file (K0,
# plan/phase7_kernel_config.md).
#
# Run as a build-time step (not just at configure time), same shape as
# gen_build_id.cmake, so an edited board file is picked up without a
# re-configure. The file is only rewritten when its contents change, so an
# unchanged config does not force a rebuild.
#
# The *schema* -- which CONFIG_* keys exist, and which are mandatory -- lives
# here, not in the board files. That keeps each board file a flat, diffable
# list of facts ("is this number right") rather than something that also has
# to get the shape right.
#
# Inputs: BOARD (path to the board-*.cmake file), OUT (header path to write),
# ENABLE_CC / ENABLE_ED (ON/OFF feature flags, F0, plan/phase8_feature_flags.md
# -- build persona choices, not board facts, so they arrive as generator
# inputs rather than living in the board file).

if(NOT DEFINED BOARD OR NOT EXISTS "${BOARD}")
    message(FATAL_ERROR "gen_config.cmake: board file not found: '${BOARD}'")
endif()
if(NOT DEFINED ENABLE_CC OR NOT DEFINED ENABLE_ED)
    message(FATAL_ERROR "gen_config.cmake: ENABLE_CC and ENABLE_ED are required")
endif()

include("${BOARD}")

# Mandatory on every target that has a board file at all.
foreach(_key CONFIG_PALLOC_MAX_PAGES CONFIG_UART0_BASE)
    if(NOT DEFINED ${_key})
        message(FATAL_ERROR "gen_config.cmake: ${BOARD} is missing required key ${_key}")
    endif()
endforeach()

if(ENABLE_CC)
    set(CONFIG_ENABLE_CC 1)
else()
    set(CONFIG_ENABLE_CC 0)
endif()
if(ENABLE_ED)
    set(CONFIG_ENABLE_ED 1)
else()
    set(CONFIG_ENABLE_ED 0)
endif()

# Optional -- only a board with real GPIO pins to map (RP2350 today) sets
# these. Emitted if present, skipped otherwise: a QEMU target's virtio
# devices have no pins to describe.
set(_optional_keys
    CONFIG_UART0_TX_GPIO CONFIG_UART0_RX_GPIO
    CONFIG_SPI1_BASE CONFIG_SPI1_SCK_GPIO CONFIG_SPI1_MOSI_GPIO
    CONFIG_SPI1_MISO_GPIO CONFIG_SPI1_CS_GPIO
    CONFIG_LED_ONBOARD_GPIO CONFIG_LED_EXT_GPIO
    CONFIG_SPI0_BASE CONFIG_ST7735_SCK_GPIO CONFIG_ST7735_MOSI_GPIO
    CONFIG_ST7735_CS_GPIO CONFIG_ST7735_DC_GPIO CONFIG_ST7735_RST_GPIO
)

set(_content "/* Generated by cmake/gen_config.cmake from ${BOARD} -- do not edit. */\n")
string(APPEND _content "#ifndef LUGALOS_CONFIG_H\n#define LUGALOS_CONFIG_H\n\n")
string(APPEND _content "#define CONFIG_PALLOC_MAX_PAGES ${CONFIG_PALLOC_MAX_PAGES}\n")
string(APPEND _content "#define CONFIG_UART0_BASE ${CONFIG_UART0_BASE}\n")
string(APPEND _content "#define CONFIG_ENABLE_CC ${CONFIG_ENABLE_CC}\n")
string(APPEND _content "#define CONFIG_ENABLE_ED ${CONFIG_ENABLE_ED}\n")
foreach(_key ${_optional_keys})
    if(DEFINED ${_key})
        string(APPEND _content "#define ${_key} ${${_key}}\n")
    endif()
endforeach()
string(APPEND _content "\n#endif /* LUGALOS_CONFIG_H */\n")

set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
