# Generates lugalos_build_id.h with a git-derived build identifier.
#
# Run as a build-time step (not just at configure time) so the id tracks
# commits without needing a re-configure -- the hardware-in-the-loop suite in
# tests/hw/ uses it to tell "the board is running what I just built" from
# "the board is running something older", a distinction that cost a wasted
# flash-and-measure cycle before it existed.
#
# The file is only rewritten when its contents change, so an unchanged id
# does not force a full rebuild on every `make`.

set(_count "0")
set(_hash "nogit")
set(_dirty "")

find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} rev-list --count HEAD
        WORKING_DIRECTORY ${SRC} OUTPUT_VARIABLE _c
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _c)
        set(_count "${_c}")
    endif()

    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short=8 HEAD
        WORKING_DIRECTORY ${SRC} OUTPUT_VARIABLE _h
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _h)
        set(_hash "${_h}")
    endif()

    # A '+' suffix marks a build from a tree with uncommitted changes. Without
    # it, two different binaries could report the same id -- precisely the
    # ambiguity this exists to remove.
    execute_process(COMMAND ${GIT_EXECUTABLE} status --porcelain
        WORKING_DIRECTORY ${SRC} OUTPUT_VARIABLE _st
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_st)
        set(_dirty "+")
    endif()
endif()

set(_content "/* Generated by cmake/gen_build_id.cmake -- do not edit. */\n")
string(APPEND _content "#ifndef LUGALOS_BUILD_ID_H\n#define LUGALOS_BUILD_ID_H\n")
string(APPEND _content "#define LUGALOS_BUILD_ID \"${_count}.${_hash}${_dirty}\"\n")
string(APPEND _content "#endif\n")

set(_old "")
if(EXISTS ${OUT})
    file(READ ${OUT} _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE ${OUT} "${_content}")
endif()
